from selenium import webdriver
import time
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.maximize_window()
time.sleep(2)
driver.get(url="https://www.saucedemo.com/v1/")
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'input[data-test="username"]').send_keys("standard_user")
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'input[data-test="password"]').send_keys("secret_sauce")
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'input[id="login-button"]').click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'div[class="bm-burger-button"]>button').click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'a[id="inventory_sidebar_link"]').click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'button[class="btn_primary btn_inventory"]').click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'path[fill="currentColor"]').click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'a[class="btn_action checkout_button"]').click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'input[id="first-name"]').send_keys("Maruti")
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'input[id="last-name"]').send_keys("AS")
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'input[id="postal-code"]').send_keys("560000")
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'input[class="btn_primary cart_button"]').click()
time.sleep(2)
driver.find_element(By.CSS_SELECTOR, 'a[class="btn_action cart_button"]').click()
time.sleep(2)
driver.find_element(By.XPATH, 'div[class="bm-burger-button"]>button').click()
time.sleep(2)
driver.find_element(By.ID, "logout_sidebar_link").click()
time.sleep(2)
driver.quit()