from selenium import webdriver
import time
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.maximize_window()
time.sleep(2)
driver.get(url="https://www.saucedemo.com/v1/")
time.sleep(2)
driver.find_element(By.XPATH, '//input[@id="user-name"]').send_keys("standard_user")
time.sleep(2)
driver.find_element(By.XPATH, '//input[@id="password"]').send_keys("secret_sauce")
time.sleep(2)
driver.find_element(By.XPATH, '//input[@id="login-button"]').click()
time.sleep(2)
driver.find_element(By.XPATH, '//button[@class="btn_primary btn_inventory"]').click()
time.sleep(2)
driver.find_element(By.XPATH, '//div[@id="shopping_cart_container"]').click() #//*[name()='svg']
time.sleep(2)
driver.find_element(By.XPATH, '//div[@class="cart_footer"]//a[@class="btn_action checkout_button"]').click()
time.sleep(2)
driver.find_element(By.XPATH, '//input[@id="first-name"]').send_keys("Maruthi")
time.sleep(2)
driver.find_element(By.XPATH, '//input[@id="last-name"]').send_keys("AS")
time.sleep(2)
driver.find_element(By.XPATH, '//input[@id="postal-code"]').send_keys("560000")
time.sleep(2)
driver.find_element(By.XPATH, '//input[@class="btn_primary cart_button"]').click()
time.sleep(2)
driver.find_element(By.XPATH, '//a[@class="btn_action cart_button"]').click()
time.sleep(2)
driver.find_element(By.XPATH, '//div[@class="bm-burger-button"]').click()
time.sleep(2)
driver.find_element(By.XPATH, '//a[@id="logout_sidebar_link"]').click()
time.sleep(2)
print("Execution completed successfully")
driver.quit()